### ISSUE TITLE
Convert to service

### ISSUE THREAD

**Issue by davebanthorpe** [Expecho/Self-Hosted-Asp.Net-WebHooks#3]
Hi - can you please advise how to convert some of your code to run as a service? I just want a service that runs a webhook that I can POST to from Postman. 

I tested your code as-is and just ran the Receiver and was able to post to it without the WebApiHost running. So do I just only need the Receiver code?

-Dave

**Comment by Expecho** [comment]
> Hi - can you please advise how to convert some of your code to run as a service? I just want a service that runs a webhook that I can POST to from Postman.


Writing a windows service is [well documented](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer). You can take most of the code, just make sure you start the webhook in the [`OnStart`](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer) method.

> I tested your code as-is and just ran the Receiver and was able to post to it without the WebApiHost running. So do I just only need the Receiver code?

The receiver hosts a public accesible API, if that is your primarily goal then yes, you only need the code of the Receiver. But you do not have web hook functionality then. The Sender is there to make sure that when a given event occurs the api of the receiver is called.
