### ISSUE TITLE
The secret key

### ISSUE THREAD

**Issue by Dagasson** [Expecho/Self-Hosted-Asp.Net-WebHooks#4]
Hi, after looking at your project, I did not fully understand if the secret key played some role in it. If so, can you explain which one?
I tried to enter different values in App.Config and when registering the hook, but did not notice any changes.

-Arthur)

**Comment by Expecho** [comment]
The secret key plays a role when implementing a custom `WebHookHandler`. See [CustomWebHookHandler](https://github.com/Expecho/Self-Hosted-Asp.Net-WebHooks/blob/master/Receiver/CustomWebHookHandler.cs) for an example.

If the key of the client does not match the key of the server the webhook fails:

> The WebHook signature provided by the 'ms-signature' header field does not match the value expected by the 'CustomWebHookReceiver' receiver. WebHook request is invalid.
