### ISSUE TITLE
Error "The program does not contain a static method "Main", suitable for the entry point."

### ISSUE THREAD

**Issue by it19862** [Expecho/Self-Hosted-Asp.Net-WebHooks#6]
VS - 2017 
I'll get the program, get an error
Error: "The program does not contain a static method "Main", suitable for the entry point."

![2019-06-30_00-00-54](https://user-images.githubusercontent.com/18245828/60389474-47c9f580-9aca-11e9-9382-2508a81795d4.png)

**Comment by Expecho** [comment]
having an `async` man is supported in c# 7.1 and up. Fixed the project settings.
