### ISSUE TITLE
Program does not contain a static 'Main' method suitable for an entry point	

### ISSUE THREAD

**Issue by vamichael** [Expecho/Self-Hosted-Asp.Net-WebHooks#7]
VS2015

I'm getting this error for both the Receiver and WebAPI host projects as well as the following:

> The name '_' does not exist in the current context	

For the Receiver in Self-Hosted-Asp.Net-WebHooks\Receiver\Startup.cs	13	Active

**Comment by Expecho** [comment]
It is a C# 7.1 feature, see [this](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-1). You will need to use Visual Studio 2017 Update 3 (version 15.3) or higher to use this.

There was once a version that used blocking calls to async methods, see [this point in time](https://github.com/Expecho/Self-Hosted-Asp.Net-WebHooks/blob/cbcbb69299968dff6662b79a41220777b029f92c/Receiver/Program.cs).
